---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Single Page
- type: document
  path: _pages/index.html
  label: Homepage
- type: document
  path: _data/mainnav.yml
  label: Menu
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: npm run build
  output_directory: _site
