---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: _blog
  label: Blog
  create: documents
  match: "**/*"
- type: heading
  label: Single Page
- type: document
  path: _pages/index.html
  label: Homepage
- type: document
  path: _pages/work.html
  label: Work
- type: document
  path: _pages/skills.html
  label: Skills & XP
- type: document
  path: _pages/contact.html
  label: Contact
- type: heading
  label: Blog
- type: heading
  label: Includes
- type: document
  path: _includes/footer.html
  label: Footer
- type: heading
  label: Data
- type: document
  path: _data/mainnav.yml
  label: Menu
- type: document
  path: _data/experience.yml
  label: Experience
- type: document
  path: _data/skills.yml
  label: Skills
upload_dir: assets/img/Uploads
public_path: assets/img/Uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: npm run build
  output_directory: _site
