---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Single Page
- type: document
  path: _pages/index.html
  label: Homepage
- type: document
  path: _pages/work.html
  label: Work
  match: "**/*"
- type: document
  path: _pages/skills.html
  label: Skills & XP
  match: "**/*"
- type: document
  path: _pages/contact.html
  label: Contact
  match: "**/*"
- type: heading
  label: Data
- type: document
  path: _data/mainnav.yml
  label: Menu
- type: document
  path: _data/experience.yml
  label: Experience
  match: "**/*"
- type: document
  path: _data/skills.yml
  label: Skills
  match: "**/*"
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: npm run build
  output_directory: _site
