---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Test
  create: all
  match: "**/*"
  templates:
  - this-is-a-page
- type: document
  path: _pages/index.html
  label: Homepage
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
